brisca:
  database:
    url: unll
    username: unll
    password: unll
  jwt:
    secret: ChkJXWvcspEVoiIQa5OaDZxXaHdM9YbW
    expiration: 3000

cosmos-client:
  baseUrl: https://briscas.documents.azure.com:443/
  appId: cosmos_db
  environment: nonprod
  svcId: master
  svcPassword: ${COSMOS_DB_PASSWORD}
  retrycount: 2