brisca:
  database:
    url: unll
    username: unll
    password: unll
  jwt:
    secret: ChkJXWvcspEVoiIQa5OaDZxXaHdM9YbW
    expiration: 3000

azure:
  cosmosdb:
    key: ${COSMOS_DB_PASSWORD}
    appId: briscas-core
    uri: https://briscas.documents.azure.com:443/
    database: nonprod
    allow-telemetry: false
    connectTimeoutInSecs: 60
    readTimeoutInSecs: 5
